---
- hosts: docker
  tasks:

    - name: Create main dir
      file:
        path: /home/daou_docker/exporters
        state: directory

    - name: Create tomcat dir
      file:
        path: /home/daou_docker/exporters/tomcat
        state: directory

    - name: Copy tomcat
      template:
        src: "/home/daou_docker/jmx-exporter/docker-compose.yml"
        dest: "/home/daou_docker/exporters/tomcat"


