---
- hosts: exporter
  gather_facts: no
  tasks:

    - name: Create main dir
      file:
        path: /home/daou_docker/exporters
        state: directory

    - name: Install packages
      vars:
        ansible_python_interpreter: /usr/bin/python2.7
      yum:
        name:
          - wget
        state: latest

    - name: Install docker
      vars:
        ansible_python_interpreter: /usr/bin/python2.7
      yum:
        name: docker
        state: latest

    - name: Install docker-compose
      shell:
        cmd: curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        warn: false
          #- name: Install docker-compose
          #get_url:
          #url: https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)
          #dest: /usr/local/bin/docker-compose


          #- name: Chmod docker-compose
          #shell:
          #cmd: chmod +x /usr/local/bin/docker-compose

    - name: Chmod docker-compose
      file:
        path: "/usr/local/bin/docker-compose"
        mode: 0755

    - name: Make link docker-compose
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link

    - name: Start docker
      service:
        name: docker
        state: started


